# coding: utf-8

"""
    Open Data Portal (ODP) API

    The Open Data Portal (ODP) API allows you to extract USPTO data at no cost - with several ways to do it. To learn about the ODP API Rate Limits, please visit to the <a href=\"https://data.uspto.gov/apis/api-rate-limits\" target=\"_blank\">API Rate Limits page</a>. <br><br> <b>Before proceeding</b>, you must have an ODP API key in order to access these Swagger UI resources. Once you have obtained an API key, you can pass the API key into a REST API call in the x-api-key header of the request. For more details and steps to generate an API key visit to the <a href=\"https://data.uspto.gov/apis/getting-started\" target=\"_blank\">Getting Started page</a>.<br><br>For example, the request to access patent data for an application might look like as below.<br><br><code>curl -X \"GET\" \"https://api.uspto.gov/api/v1/patent/applications/14412875\" -H \"X-API-KEY:YOUR_API_KEY\"</code><br><br></br><code>curl -X \"POST\" \"https://api.uspto.gov/api/v1/patent/applications/search\" -H \"X-API-KEY:YOUR_API_KEY\" -d \"{\\\\\"q\\\\\":\\\\\"applicationMetaData.applicationTypeLabelName:Utility\\\\\"}\"</br></code>

    The version of the OpenAPI document: 1.0.0
    Contact: data@uspto.gov
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "openapi-client"
VERSION = "1.0.0"
PYTHON_REQUIRES = ">= 3.9"
REQUIRES = [
    "urllib3 >= 2.1.0, < 3.0.0",
    "python-dateutil >= 2.8.2",
    "pydantic >= 2",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="Open Data Portal (ODP) API",
    author="USPTO",
    author_email="data@uspto.gov",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "Open Data Portal (ODP) API"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description_content_type='text/markdown',
    long_description="""\
    The Open Data Portal (ODP) API allows you to extract USPTO data at no cost - with several ways to do it. To learn about the ODP API Rate Limits, please visit to the &lt;a href&#x3D;\&quot;https://data.uspto.gov/apis/api-rate-limits\&quot; target&#x3D;\&quot;_blank\&quot;&gt;API Rate Limits page&lt;/a&gt;. &lt;br&gt;&lt;br&gt; &lt;b&gt;Before proceeding&lt;/b&gt;, you must have an ODP API key in order to access these Swagger UI resources. Once you have obtained an API key, you can pass the API key into a REST API call in the x-api-key header of the request. For more details and steps to generate an API key visit to the &lt;a href&#x3D;\&quot;https://data.uspto.gov/apis/getting-started\&quot; target&#x3D;\&quot;_blank\&quot;&gt;Getting Started page&lt;/a&gt;.&lt;br&gt;&lt;br&gt;For example, the request to access patent data for an application might look like as below.&lt;br&gt;&lt;br&gt;&lt;code&gt;curl -X \&quot;GET\&quot; \&quot;https://api.uspto.gov/api/v1/patent/applications/14412875\&quot; -H \&quot;X-API-KEY:YOUR_API_KEY\&quot;&lt;/code&gt;&lt;br&gt;&lt;br&gt;&lt;/br&gt;&lt;code&gt;curl -X \&quot;POST\&quot; \&quot;https://api.uspto.gov/api/v1/patent/applications/search\&quot; -H \&quot;X-API-KEY:YOUR_API_KEY\&quot; -d \&quot;{\\\\\&quot;q\\\\\&quot;:\\\\\&quot;applicationMetaData.applicationTypeLabelName:Utility\\\\\&quot;}\&quot;&lt;/br&gt;&lt;/code&gt;
    """,  # noqa: E501
    package_data={"openapi_client": ["py.typed"]},
)