# coding: utf-8

"""
    Open Data Portal (ODP) API

    The Open Data Portal (ODP) API allows you to extract USPTO data at no cost - with several ways to do it. To learn about the ODP API Rate Limits, please visit to the <a href=\"https://data.uspto.gov/apis/api-rate-limits\" target=\"_blank\">API Rate Limits page</a>. <br><br> <b>Before proceeding</b>, you must have an ODP API key in order to access these Swagger UI resources. Once you have obtained an API key, you can pass the API key into a REST API call in the x-api-key header of the request. For more details and steps to generate an API key visit to the <a href=\"https://data.uspto.gov/apis/getting-started\" target=\"_blank\">Getting Started page</a>.<br><br>For example, the request to access patent data for an application might look like as below.<br><br><code>curl -X \"GET\" \"https://api.uspto.gov/api/v1/patent/applications/14412875\" -H \"X-API-KEY:YOUR_API_KEY\"</code><br><br></br><code>curl -X \"POST\" \"https://api.uspto.gov/api/v1/patent/applications/search\" -H \"X-API-KEY:YOUR_API_KEY\" -d \"{\\\\\"q\\\\\":\\\\\"applicationMetaData.applicationTypeLabelName:Utility\\\\\"}\"</br></code>

    The version of the OpenAPI document: 1.0.0
    Contact: data@uspto.gov
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.document_bag_document_bag_inner import DocumentBagDocumentBagInner

class TestDocumentBagDocumentBagInner(unittest.TestCase):
    """DocumentBagDocumentBagInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DocumentBagDocumentBagInner:
        """Test DocumentBagDocumentBagInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DocumentBagDocumentBagInner`
        """
        model = DocumentBagDocumentBagInner()
        if include_optional:
            return DocumentBagDocumentBagInner(
                application_number_text = '16123123',
                official_date = '2020-08-31T01:20:29.000-0400',
                document_identifier = 'LDXBTPQ7XBLUEX3',
                document_code = 'WFEE',
                document_code_description_text = 'Fee Worksheet (SB06)',
                document_direction_category = 'INTERNAL',
                download_option_bag = [
                    openapi_client.models.document_bag_document_bag_inner_download_option_bag_inner.DocumentBag_documentBag_inner_downloadOptionBag_inner(
                        mime_type_identifier = 'PDF', 
                        download_url = 'https://api.uspto.gov/api/v1/patent/application/documents/16123123/LDXBTPQ7XBLUEX3.pdf', 
                        page_total_quantity = 2, )
                    ]
            )
        else:
            return DocumentBagDocumentBagInner(
        )
        """

    def testDocumentBagDocumentBagInner(self):
        """Test DocumentBagDocumentBagInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
