# coding: utf-8

"""
    Open Data Portal (ODP) API

    The Open Data Portal (ODP) API allows you to extract USPTO data at no cost - with several ways to do it. To learn about the ODP API Rate Limits, please visit to the <a href=\"https://data.uspto.gov/apis/api-rate-limits\" target=\"_blank\">API Rate Limits page</a>. <br><br> <b>Before proceeding</b>, you must have an ODP API key in order to access these Swagger UI resources. Once you have obtained an API key, you can pass the API key into a REST API call in the x-api-key header of the request. For more details and steps to generate an API key visit to the <a href=\"https://data.uspto.gov/apis/getting-started\" target=\"_blank\">Getting Started page</a>.<br><br>For example, the request to access patent data for an application might look like as below.<br><br><code>curl -X \"GET\" \"https://api.uspto.gov/api/v1/patent/applications/14412875\" -H \"X-API-KEY:YOUR_API_KEY\"</code><br><br></br><code>curl -X \"POST\" \"https://api.uspto.gov/api/v1/patent/applications/search\" -H \"X-API-KEY:YOUR_API_KEY\" -d \"{\\\\\"q\\\\\":\\\\\"applicationMetaData.applicationTypeLabelName:Utility\\\\\"}\"</br></code>

    The version of the OpenAPI document: 1.0.0
    Contact: data@uspto.gov
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.patent_search_api import PatentSearchApi


class TestPatentSearchApi(unittest.TestCase):
    """PatentSearchApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PatentSearchApi()

    def tearDown(self) -> None:
        pass

    def test_api_v1_patent_applications_application_number_text_adjustment_get(self) -> None:
        """Test case for api_v1_patent_applications_application_number_text_adjustment_get

        Get patent term adjustment data for an application number
        """
        pass

    def test_api_v1_patent_applications_application_number_text_assignment_get(self) -> None:
        """Test case for api_v1_patent_applications_application_number_text_assignment_get

        Get patent assignment data for an application number
        """
        pass

    def test_api_v1_patent_applications_application_number_text_associated_documents_get(self) -> None:
        """Test case for api_v1_patent_applications_application_number_text_associated_documents_get

        Associated (pgpub, grant) documents meta-data for an application
        """
        pass

    def test_api_v1_patent_applications_application_number_text_attorney_get(self) -> None:
        """Test case for api_v1_patent_applications_application_number_text_attorney_get

        Get attorney/agent data for an application number
        """
        pass

    def test_api_v1_patent_applications_application_number_text_continuity_get(self) -> None:
        """Test case for api_v1_patent_applications_application_number_text_continuity_get

        Get continuity data for an application number
        """
        pass

    def test_api_v1_patent_applications_application_number_text_documents_get(self) -> None:
        """Test case for api_v1_patent_applications_application_number_text_documents_get

        Documents details for an application number
        """
        pass

    def test_api_v1_patent_applications_application_number_text_foreign_priority_get(self) -> None:
        """Test case for api_v1_patent_applications_application_number_text_foreign_priority_get

        Get foreign-priority data for an application number
        """
        pass

    def test_api_v1_patent_applications_application_number_text_get(self) -> None:
        """Test case for api_v1_patent_applications_application_number_text_get

        Patent application data for a provided application number
        """
        pass

    def test_api_v1_patent_applications_application_number_text_meta_data_get(self) -> None:
        """Test case for api_v1_patent_applications_application_number_text_meta_data_get

        Get patent application meta data
        """
        pass

    def test_api_v1_patent_applications_application_number_text_transactions_get(self) -> None:
        """Test case for api_v1_patent_applications_application_number_text_transactions_get

        Get transaction data for an application number
        """
        pass

    def test_api_v1_patent_applications_search_download_get(self) -> None:
        """Test case for api_v1_patent_applications_search_download_get

        Patent application search by supplying query parameters
        """
        pass

    def test_api_v1_patent_applications_search_download_post(self) -> None:
        """Test case for api_v1_patent_applications_search_download_post

        Download patent data by supplying json payload
        """
        pass

    def test_api_v1_patent_applications_search_get(self) -> None:
        """Test case for api_v1_patent_applications_search_get

        Patent application search by supplying query parameters
        """
        pass

    def test_api_v1_patent_applications_search_post(self) -> None:
        """Test case for api_v1_patent_applications_search_post

        Search patent applications by supplying json payload
        """
        pass

    def test_api_v1_patent_status_codes_get(self) -> None:
        """Test case for api_v1_patent_status_codes_get

        Search patent application status codes and status code description
        """
        pass

    def test_api_v1_patent_status_codes_post(self) -> None:
        """Test case for api_v1_patent_status_codes_post

        Search patent application status codes and status code description
        """
        pass


if __name__ == '__main__':
    unittest.main()
