# coding: utf-8

"""
    Open Data Portal (ODP) API

    The Open Data Portal (ODP) API allows you to extract USPTO data at no cost - with several ways to do it. To learn about the ODP API Rate Limits, please visit to the <a href=\"https://data.uspto.gov/apis/api-rate-limits\" target=\"_blank\">API Rate Limits page</a>. <br><br> <b>Before proceeding</b>, you must have an ODP API key in order to access these Swagger UI resources. Once you have obtained an API key, you can pass the API key into a REST API call in the x-api-key header of the request. For more details and steps to generate an API key visit to the <a href=\"https://data.uspto.gov/apis/getting-started\" target=\"_blank\">Getting Started page</a>.<br><br>For example, the request to access patent data for an application might look like as below.<br><br><code>curl -X \"GET\" \"https://api.uspto.gov/api/v1/patent/applications/14412875\" -H \"X-API-KEY:YOUR_API_KEY\"</code><br><br></br><code>curl -X \"POST\" \"https://api.uspto.gov/api/v1/patent/applications/search\" -H \"X-API-KEY:YOUR_API_KEY\" -d \"{\\\\\"q\\\\\":\\\\\"applicationMetaData.applicationTypeLabelName:Utility\\\\\"}\"</br></code>

    The version of the OpenAPI document: 1.0.0
    Contact: data@uspto.gov
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.api_v1_patent_applications_application_number_text_attorney_get200_response_patent_file_wrapper_data_bag_inner import ApiV1PatentApplicationsApplicationNumberTextAttorneyGet200ResponsePatentFileWrapperDataBagInner
from typing import Optional, Set
from typing_extensions import Self

class ApiV1PatentApplicationsApplicationNumberTextAttorneyGet200Response(BaseModel):
    """
    ApiV1PatentApplicationsApplicationNumberTextAttorneyGet200Response
    """ # noqa: E501
    count: Optional[StrictInt] = None
    patent_file_wrapper_data_bag: Optional[List[ApiV1PatentApplicationsApplicationNumberTextAttorneyGet200ResponsePatentFileWrapperDataBagInner]] = Field(default=None, alias="patentFileWrapperDataBag")
    __properties: ClassVar[List[str]] = ["count", "patentFileWrapperDataBag"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ApiV1PatentApplicationsApplicationNumberTextAttorneyGet200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in patent_file_wrapper_data_bag (list)
        _items = []
        if self.patent_file_wrapper_data_bag:
            for _item_patent_file_wrapper_data_bag in self.patent_file_wrapper_data_bag:
                if _item_patent_file_wrapper_data_bag:
                    _items.append(_item_patent_file_wrapper_data_bag.to_dict())
            _dict['patentFileWrapperDataBag'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ApiV1PatentApplicationsApplicationNumberTextAttorneyGet200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "count": obj.get("count"),
            "patentFileWrapperDataBag": [ApiV1PatentApplicationsApplicationNumberTextAttorneyGet200ResponsePatentFileWrapperDataBagInner.from_dict(_item) for _item in obj["patentFileWrapperDataBag"]] if obj.get("patentFileWrapperDataBag") is not None else None
        })
        return _obj


