# coding: utf-8

"""
    Open Data Portal (ODP) API

    The Open Data Portal (ODP) API allows you to extract USPTO data at no cost - with several ways to do it. To learn about the ODP API Rate Limits, please visit to the <a href=\"https://data.uspto.gov/apis/api-rate-limits\" target=\"_blank\">API Rate Limits page</a>. <br><br> <b>Before proceeding</b>, you must have an ODP API key in order to access these Swagger UI resources. Once you have obtained an API key, you can pass the API key into a REST API call in the x-api-key header of the request. For more details and steps to generate an API key visit to the <a href=\"https://data.uspto.gov/apis/getting-started\" target=\"_blank\">Getting Started page</a>.<br><br>For example, the request to access patent data for an application might look like as below.<br><br><code>curl -X \"GET\" \"https://api.uspto.gov/api/v1/patent/applications/14412875\" -H \"X-API-KEY:YOUR_API_KEY\"</code><br><br></br><code>curl -X \"POST\" \"https://api.uspto.gov/api/v1/patent/applications/search\" -H \"X-API-KEY:YOUR_API_KEY\" -d \"{\\\\\"q\\\\\":\\\\\"applicationMetaData.applicationTypeLabelName:Utility\\\\\"}\"</br></code>

    The version of the OpenAPI document: 1.0.0
    Contact: data@uspto.gov
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.child_continuity_data import ChildContinuityData
from openapi_client.models.parent_continuity_data import ParentContinuityData
from typing import Optional, Set
from typing_extensions import Self

class ApiV1PatentApplicationsApplicationNumberTextContinuityGet200ResponsePatentFileWrapperDataBagInner(BaseModel):
    """
    ApiV1PatentApplicationsApplicationNumberTextContinuityGet200ResponsePatentFileWrapperDataBagInner
    """ # noqa: E501
    application_number_text: Optional[StrictStr] = Field(default=None, description="Free format of application number", alias="applicationNumberText")
    parent_continuity_bag: Optional[List[ParentContinuityData]] = Field(default=None, alias="parentContinuityBag")
    child_continuity_bag: Optional[List[ChildContinuityData]] = Field(default=None, alias="childContinuityBag")
    request_identifier: Optional[StrictStr] = Field(default=None, alias="requestIdentifier")
    __properties: ClassVar[List[str]] = ["applicationNumberText", "parentContinuityBag", "childContinuityBag", "requestIdentifier"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ApiV1PatentApplicationsApplicationNumberTextContinuityGet200ResponsePatentFileWrapperDataBagInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in parent_continuity_bag (list)
        _items = []
        if self.parent_continuity_bag:
            for _item_parent_continuity_bag in self.parent_continuity_bag:
                if _item_parent_continuity_bag:
                    _items.append(_item_parent_continuity_bag.to_dict())
            _dict['parentContinuityBag'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in child_continuity_bag (list)
        _items = []
        if self.child_continuity_bag:
            for _item_child_continuity_bag in self.child_continuity_bag:
                if _item_child_continuity_bag:
                    _items.append(_item_child_continuity_bag.to_dict())
            _dict['childContinuityBag'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ApiV1PatentApplicationsApplicationNumberTextContinuityGet200ResponsePatentFileWrapperDataBagInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "applicationNumberText": obj.get("applicationNumberText"),
            "parentContinuityBag": [ParentContinuityData.from_dict(_item) for _item in obj["parentContinuityBag"]] if obj.get("parentContinuityBag") is not None else None,
            "childContinuityBag": [ChildContinuityData.from_dict(_item) for _item in obj["childContinuityBag"]] if obj.get("childContinuityBag") is not None else None,
            "requestIdentifier": obj.get("requestIdentifier")
        })
        return _obj


