# coding: utf-8

"""
    Open Data Portal (ODP) API

    The Open Data Portal (ODP) API allows you to extract USPTO data at no cost - with several ways to do it. To learn about the ODP API Rate Limits, please visit to the <a href=\"https://data.uspto.gov/apis/api-rate-limits\" target=\"_blank\">API Rate Limits page</a>. <br><br> <b>Before proceeding</b>, you must have an ODP API key in order to access these Swagger UI resources. Once you have obtained an API key, you can pass the API key into a REST API call in the x-api-key header of the request. For more details and steps to generate an API key visit to the <a href=\"https://data.uspto.gov/apis/getting-started\" target=\"_blank\">Getting Started page</a>.<br><br>For example, the request to access patent data for an application might look like as below.<br><br><code>curl -X \"GET\" \"https://api.uspto.gov/api/v1/patent/applications/14412875\" -H \"X-API-KEY:YOUR_API_KEY\"</code><br><br></br><code>curl -X \"POST\" \"https://api.uspto.gov/api/v1/patent/applications/search\" -H \"X-API-KEY:YOUR_API_KEY\" -d \"{\\\\\"q\\\\\":\\\\\"applicationMetaData.applicationTypeLabelName:Utility\\\\\"}\"</br></code>

    The version of the OpenAPI document: 1.0.0
    Contact: data@uspto.gov
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.record_attorney_attorney_bag_inner import RecordAttorneyAttorneyBagInner
from openapi_client.models.record_attorney_customer_number_correspondence_data_inner import RecordAttorneyCustomerNumberCorrespondenceDataInner
from openapi_client.models.record_attorney_power_of_attorney_bag_inner import RecordAttorneyPowerOfAttorneyBagInner
from typing import Optional, Set
from typing_extensions import Self

class RecordAttorney(BaseModel):
    """
    An attorney selected by the applicant or owner of an intellectual property to represent them before the national office.
    """ # noqa: E501
    customer_number_correspondence_data: Optional[List[RecordAttorneyCustomerNumberCorrespondenceDataInner]] = Field(default=None, description="Correspondence address of the application inherited from the customer.", alias="customerNumberCorrespondenceData")
    power_of_attorney_bag: Optional[List[RecordAttorneyPowerOfAttorneyBagInner]] = Field(default=None, alias="powerOfAttorneyBag")
    attorney_bag: Optional[List[RecordAttorneyAttorneyBagInner]] = Field(default=None, alias="attorneyBag")
    __properties: ClassVar[List[str]] = ["customerNumberCorrespondenceData", "powerOfAttorneyBag", "attorneyBag"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RecordAttorney from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in customer_number_correspondence_data (list)
        _items = []
        if self.customer_number_correspondence_data:
            for _item_customer_number_correspondence_data in self.customer_number_correspondence_data:
                if _item_customer_number_correspondence_data:
                    _items.append(_item_customer_number_correspondence_data.to_dict())
            _dict['customerNumberCorrespondenceData'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in power_of_attorney_bag (list)
        _items = []
        if self.power_of_attorney_bag:
            for _item_power_of_attorney_bag in self.power_of_attorney_bag:
                if _item_power_of_attorney_bag:
                    _items.append(_item_power_of_attorney_bag.to_dict())
            _dict['powerOfAttorneyBag'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in attorney_bag (list)
        _items = []
        if self.attorney_bag:
            for _item_attorney_bag in self.attorney_bag:
                if _item_attorney_bag:
                    _items.append(_item_attorney_bag.to_dict())
            _dict['attorneyBag'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RecordAttorney from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "customerNumberCorrespondenceData": [RecordAttorneyCustomerNumberCorrespondenceDataInner.from_dict(_item) for _item in obj["customerNumberCorrespondenceData"]] if obj.get("customerNumberCorrespondenceData") is not None else None,
            "powerOfAttorneyBag": [RecordAttorneyPowerOfAttorneyBagInner.from_dict(_item) for _item in obj["powerOfAttorneyBag"]] if obj.get("powerOfAttorneyBag") is not None else None,
            "attorneyBag": [RecordAttorneyAttorneyBagInner.from_dict(_item) for _item in obj["attorneyBag"]] if obj.get("attorneyBag") is not None else None
        })
        return _obj


